### ISSUE TITLE
Make it possible to configure marker icon

### ISSUE THREAD

**Issue by tmotyl** [obisconcept/neos-gmaps#10]
It would be nice if the integrator could set custom marker icon image.
```
var marker = new google.maps.Marker({
                        map: map,
                        icon: imagePath,
                        position: latlang
                    });
```

**Comment by pgnonick** [comment]
Thanks for the suggestion. We added it for the next version :) Actually we rebuild the blog plugin.

**Comment by tmotyl** [comment]
good to know, looking forward to it.

**Comment by MCStreetguy** [comment]
Closing super-old issues. Please re-open if still relevant.
