### ISSUE TITLE
Marker fields are not properly escaped

### ISSUE THREAD

**Issue by tmotyl** [obisconcept/neos-gmaps#6]
Marker fields (e.g. title) are not properly escaped - putting double quote results in a wrong json and breaks the whole map.

How to reproduce:
- put " inside marker title
- save and refresh page

The same could be true for single quote or other special characters

**Comment by pgnonick** [comment]
Hi,
thanks for reporting this bug.
We will publish an update soon :)

**Comment by MCStreetguy** [comment]
Closing super-old issues. Please re-open if still relevant.
