### ISSUE TITLE
Coordinates should be geocoded on marker save.

### ISSUE THREAD

**Issue by tmotyl** [obisconcept/neos-gmaps#7]
Currently if you have multiple markers on one map, geocoding will fail for some of them because of the Google API limits.
To overcome this problem, address of the marker should be geoencoded on marker edit and saved in the marker node.
Right now a request to Google API is made for every marker on every page refresh.

**Comment by pgnonick** [comment]
Hi,
thanks for your advice :)
We will publish an update soon.

**Comment by MCStreetguy** [comment]
Closing super-old issues. Please re-open if still relevant.
